apiVersion: v1
kind: Service
metadata:
  name: {{ include "jevbox.name" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "jevbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
