export const providerCatalog = [
  { id: "openai", label: "OpenAI", model: "gpt-6-luna" },
  { id: "anthropic", label: "Anthropic", model: "claude-sonnet-5-5" },
  { id: "google", label: "Google Gemini", model: "gemini-3.8-flash" },
  { id: "gateway", label: "AI Gateway", model: "openai/gpt-6-luna" },
  { id: "azure", label: "Azure OpenAI", model: "", fields: ["resourceName"] },
  {
    id: "bedrock",
    label: "Amazon Bedrock",
    model: "anthropic.claude-sonnet-5-5",
    fields: ["region"],
  },
  {
    id: "vertex",
    label: "Google Vertex",
    model: "gemini-3.8-flash",
    fields: ["project", "location"],
  },
  {
    id: "anthropic-aws",
    label: "Anthropic on AWS",
    model: "claude-sonnet-5-5",
    fields: ["region"],
  },
  { id: "mistral", label: "Mistral", model: "mistral-medium-3-5" },
  { id: "groq", label: "Groq", model: "openai/gpt-oss-120b" },
  { id: "deepseek", label: "DeepSeek", model: "deepseek-flash" },
  { id: "xai", label: "xAI", model: "grok-4.7" },
  { id: "cohere", label: "Cohere", model: "command-a-plus-05-2026" },
  { id: "togetherai", label: "Together AI", model: "moonshotai/Kimi-K3" },
  {
    id: "fireworks",
    label: "Fireworks",
    model: "accounts/fireworks/models/glm-5p3-flash",
  },
  { id: "deepinfra", label: "DeepInfra", model: "moonshotai/Kimi-K3" },
  { id: "cerebras", label: "Cerebras", model: "gpt-oss-120b" },
  { id: "perplexity", label: "Perplexity", model: "sonar" },
  { id: "alibaba", label: "Alibaba", model: "qwen3.8-flash" },
  { id: "baseten", label: "Baseten", model: "zai-org/GLM-5.3" },
  { id: "minimax", label: "MiniMax", model: "MiniMax-M3.1-Flash-Preview" },
  { id: "moonshotai", label: "Moonshot AI", model: "kimi-k3" },
  { id: "zai", label: "Z.AI", model: "glm-5.3-flash" },
  { id: "huggingface", label: "Hugging Face", model: "moonshotai/Kimi-K3" },
  {
    id: "compatible",
    label: "OpenAI-compatible endpoint",
    model: "",
    fields: ["baseURL"],
  },
  {
    id: "extension",
    label: "Installed AI SDK extension",
    model: "",
    fields: ["extension"],
  },
];
