ALTER TABLE resources ADD COLUMN index_job_id UUID;
ALTER TABLE resources ADD COLUMN parse_requested BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE document_filing ADD COLUMN job_id UUID;
ALTER TABLE document_filing RENAME COLUMN lease_id TO attempt_id;
ALTER TABLE document_filing DROP COLUMN lease_until;
ALTER TABLE organization_reviews ADD COLUMN job_id UUID;
ALTER TABLE organization_reviews RENAME COLUMN lease_id TO attempt_id;
ALTER TABLE organization_reviews DROP COLUMN lease_until;
ALTER TABLE chat_turns ADD COLUMN job_id UUID;
ALTER TABLE chat_turns RENAME COLUMN lease_id TO attempt_id;
ALTER TABLE chat_turns DROP COLUMN lease_until;
DROP INDEX document_filing_queue;
DROP INDEX organization_reviews_queue;
CREATE INDEX organization_reviews_pending ON organization_reviews(org_id,owner_id,created) WHERE state='pending';
CREATE INDEX resources_index_pending ON resources(id) WHERE status IN ('queued','processing');
CREATE INDEX document_filing_pending ON document_filing(resource_id) WHERE state IN ('pending','working');
CREATE INDEX organization_reviews_unfinished ON organization_reviews(id) WHERE state IN ('pending','working');
UPDATE resources SET status='failed',error='Background processing changed. Retry indexing to continue.' WHERE status IN ('queued','processing');
UPDATE document_filing SET state='failed',attempt_id=NULL,error='Background processing changed. Retry organization to continue.' WHERE state IN ('pending','working');
UPDATE organization_reviews SET state='failed',attempt_id=NULL,error='Background processing changed. Retry organization to continue.' WHERE state IN ('pending','working');
UPDATE chat_turns SET status='failed',attempt_id=NULL,error='The answer was interrupted. Retry when you are ready.',error_status=503 WHERE status IN ('queued','retrieving','generating','cancelling');
