ALTER TABLE users ADD COLUMN role TEXT NOT NULL DEFAULT 'user';
ALTER TABLE users ADD COLUMN banned BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN ban_reason TEXT;
ALTER TABLE users ADD COLUMN ban_expires TIMESTAMPTZ;
ALTER TABLE auth_sessions ADD COLUMN impersonated_by TEXT;
